### ISSUE TITLE
JavaScript is case-sensitive and button ID is incorrect

### ISSUE THREAD

**Issue by joeveloper** [MussieTeka/Bugs-hide-and-seek#1]
The JavaScript code on this repository is using an incorrect ID for the button element. The ID in the code is "myButton" with an uppercase "B", while the actual ID of the button in the HTML is "mybutton" with a lowercase "b". This is causing the button not to work. It is important to note that JavaScript is case-sensitive, and the correct ID should be used in the code to match the ID in the HTML.

**Comment by MussieTeka** [comment]
Completed.
